import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const futura = localFont({
  src: [
    {
      path: "./fonts/FuturaLT-Book.woff2",
      weight: "400",
    },
    {
      path: "./fonts/FuturaLT-Bold.woff2",
      weight: "700",
    },
    {
      path: "./fonts/FuturaLT-CondensedBold.woff2",
      weight: "500",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={futura.className}>{children}</body>
    </html>
  );
}
